[package]
name = "md5-rs"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85.1"

[dependencies]
# None :D

[dev-dependencies]
criterion = "0.8.2"
getrandom = "0.4.3"
tempfile = "3"

[profile.dev]
overflow-checks = false

[profile.release]
lto = "fat"


[[bench]]
name = "bench-rand"
harness = false
